[WFLY-16707][WFLY-16780] Jakarta EE 10 BOMs
wildfly/boms pull request #115
Opened 2022-08-10 14:05 UTC by emmartins

Issues: https://issues.redhat.com/browse/WFLY-16707, https://issues.redhat.com/browse/WFLY-16780
Please do not merge, WIP!

2022-08-10 14:40 UTC, jamezp commented on ee/pom.xml
>                                      <artifactId>commons-io</artifactId>
This is definitely not required. I removed all requirements for `commons-io`.

2022-08-10 14:40 UTC, jamezp commented on ee/pom.xml
>                                      <artifactId>resteasy-validator-provider</artifactId>
Depending on the quickstart, this could be required.

2022-08-10 14:40 UTC, jamezp commented on ee/pom.xml
> -                                </dependency>
This would need to be changed to `org.jboss.resteasy.spring:resteasy-spring:3.0.0.Beta1`. I think we're at Alpha3 in WF, but I think an upgrade PR is coming in. Either way the group id needs to change :)

2022-08-10 14:40 UTC, jamezp commented on ee/pom.xml
>                                      <artifactId>jackson-datatype-jsr310</artifactId>
This and the other Jackson ones are only needed if we're using the `resteasy-jackson2-provider`. Even then the dependencies should come in transitively.

2022-08-10 14:40 UTC, jamezp commented on ee/pom.xml
>                                  </dependency>
Same as above with this.

2022-08-10 15:26 UTC, emmartins commented on ee/pom.xml
> -                                </dependency>
We don't use this on QS, does it makes sense to keep it in the bom tho?

2022-08-10 15:28 UTC, emmartins commented on ee/pom.xml
>                                      <artifactId>resteasy-validator-provider</artifactId>
It's not used but I will let you know when I am done with the QS changes, so you have a look at both

2022-08-10 15:29 UTC, emmartins commented on ee/pom.xml
>                                  </dependency>
Got it, thanks.

2022-08-10 15:30 UTC, jamezp commented on ee/pom.xml
> -                                </dependency>
It probably does as users might be using it. Sorry, I shouldn't mix BOM's and QS's :)

2022-08-10 15:35 UTC, emmartins commented on ee/pom.xml
>                                      <artifactId>commons-io</artifactId>
removed

2022-08-10 15:35 UTC, emmartins commented on ee/pom.xml
> -                                </dependency>
readded

2022-08-11 14:46 UTC, jamezp approved these changes

2022-08-11 14:49 UTC, bstansberry approved these changes

2022-08-11 15:05 UTC, scottmarlow requested changes

2022-08-11 15:21 UTC, scottmarlow approved these changes

2022-08-11 16:04 UTC, merged